apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-ninja-pv
  labels:
    app: s3-ninja
    type: local
spec:
  storageClassName: s3-ninja-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/s3-ninja
