apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvc-pipeline

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - job.yaml
  # Descomente a linha abaixo para habilitar execução agendada
  # - cronjob.yaml
