apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvc-pipeline-data-pvc
  namespace: dvc-pipeline
  labels:
    app: dvc-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
