apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: mlflow
  labels:
    app: mlflow
type: Opaque
stringData:
  POSTGRES_DATABASE: "mlflow"
  POSTGRES_USER: "mlflow"
  POSTGRES_PASSWORD: "your-postgres-password"
  AWS_ACCESS_KEY_ID: "your-aws-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key"
  S3_ENDPOINT_URL: "http://s3-ninja.s3-ninja.svc.cluster.local:9000"
